/**
 * Weekly journal roll-up.
 *
 * Condenses daily journals into weekly summaries to prevent accumulation.
 * After roll-up, a 30-day history becomes 4 weekly files + this week's dailies
 * instead of 30 individual files.
 *
 * Logic:
 *   1. Group daily entries by ISO week
 *   2. For each complete week (7+ days old, 3+ entries):
 *      - Synthesize: briefs, decisions, blockers, completed, next
 *      - Write YYYY-WNN.md summary
 *      - Archive original daily files
 *   3. Update journal index
 */

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod/v4";
import * as fs from "node:fs";
import * as path from "node:path";
import { resolveProject } from "../storage/project.js";
import { journalDir } from "../storage/paths.js";
import { ensureDir } from "../storage/fs-utils.js";
import { listJournalFiles, updateIndex } from "../helpers/journal-files.js";
import { extractSection } from "../helpers/sections.js";
import { stateFilePath } from "./journal-state.js";

/** Get ISO week number and year for a date string. */
export function isoWeek(dateStr: string): { year: number; week: number } {
  const d = new Date(dateStr + "T12:00:00Z"); // noon UTC to avoid timezone issues
  d.setUTCDate(d.getUTCDate() + 4 - (d.getUTCDay() || 7));
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
  return { year: d.getUTCFullYear(), week };
}

/** Format week key: "2026-W14" */
export function weekKey(dateStr: string): string {
  const { year, week } = isoWeek(dateStr);
  return `${year}-W${String(week).padStart(2, "0")}`;
}

interface RollupResult {
  weeksRolledUp: number;
  entriesArchived: number;
  summariesCreated: string[];
  skipped: string[];
}

/**
 * Group journal entries by ISO week.
 * Returns a map of weekKey → entries, sorted by date within each week.
 */
export function groupByWeek(
  entries: Array<{ date: string; file: string; dir: string }>
): Map<string, Array<{ date: string; file: string; dir: string }>> {
  const groups = new Map<string, Array<{ date: string; file: string; dir: string }>>();
  for (const entry of entries) {
    const key = weekKey(entry.date);
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(entry);
  }
  // Sort entries within each week by date ascending
  for (const [, group] of groups) {
    group.sort((a, b) => a.date.localeCompare(b.date));
  }
  return groups;
}

/**
 * Synthesize a week of journal entries into a summary.
 */
export function synthesizeWeek(
  wk: string,
  entries: Array<{ date: string; file: string; dir: string }>
): string {
  const briefs: string[] = [];
  const decisions: string[] = [];
  const blockers: string[] = [];
  const completed: string[] = [];
  const next: string[] = [];

  for (const entry of entries) {
    const content = fs.readFileSync(path.join(entry.dir, entry.file), "utf-8");
    const brief = extractSection(content, "brief");
    const decision = extractSection(content, "decisions");
    const blocker = extractSection(content, "blockers");
    const comp = extractSection(content, "completed");
    const nxt = extractSection(content, "next");

    if (brief) briefs.push(`**${entry.date}**: ${brief.split("\n").find(l => l.trim()) || ""}`);
    if (decision) decisions.push(`**${entry.date}**: ${decision.split("\n").filter(l => l.trim()).slice(0, 3).join(" | ")}`);
    if (blocker) blockers.push(`**${entry.date}**: ${blocker.split("\n").find(l => l.trim()) || ""}`);
    if (comp) completed.push(`**${entry.date}**: ${comp.split("\n").filter(l => l.trim()).slice(0, 3).join(", ")}`);
    if (nxt) next.push(`**${entry.date}**: ${nxt.split("\n").find(l => l.trim()) || ""}`);
  }

  let summary = `# ${wk} Weekly Summary\n\n`;
  summary += `> Condensed from ${entries.length} daily entries: ${entries[0].date} → ${entries[entries.length - 1].date}\n`;
  summary += `> Auto-generated by journal_rollup. Originals in archive/.\n\n`;

  summary += `## Briefs\n\n${briefs.join("\n") || "(none)"}\n\n`;
  summary += `## Completed\n\n${completed.join("\n") || "(none)"}\n\n`;
  summary += `## Decisions\n\n${decisions.join("\n") || "(none)"}\n\n`;
  summary += `## Blockers\n\n${blockers.join("\n") || "(none)"}\n\n`;
  summary += `## Next Actions (end of week)\n\n${next.length > 0 ? next[next.length - 1] : "(none)"}\n`;

  return summary;
}

export function register(server: McpServer): void {
  server.registerTool("journal_rollup", {
    title: "Weekly Journal Roll-Up",
    description:
      "Condense old daily journals into weekly summaries. " +
      "Groups entries by ISO week, synthesizes a summary, archives originals. " +
      "Prevents journal accumulation — after 30 days you have 4 weekly files instead of 30 daily files. " +
      "Only processes complete weeks that are 7+ days old with 2+ entries. Use dry_run=true to preview.",
    inputSchema: {
      min_age_days: z.number().int().default(7).describe("Only roll up weeks where ALL entries are older than this"),
      min_entries: z.number().int().default(2).describe("Minimum daily entries in a week to trigger roll-up"),
      dry_run: z.boolean().default(false).describe("Preview without writing or archiving"),
      project: z.string().default("auto"),
    },
  }, async ({ min_age_days, min_entries, dry_run, project }) => {
    const slug = await resolveProject(project);
    const entries = listJournalFiles(slug);
    const dir = journalDir(slug);
    const archiveDir = path.join(dir, "archive");

    const result: RollupResult = {
      weeksRolledUp: 0,
      entriesArchived: 0,
      summariesCreated: [],
      skipped: [],
    };

    // Group by ISO week
    const groups = groupByWeek(entries);

    for (const [wk, weekEntries] of groups) {
      // Check: already rolled up? (weekly summary file exists)
      const summaryFile = `${wk}.md`;
      if (fs.existsSync(path.join(dir, summaryFile))) {
        result.skipped.push(`${wk}: already exists`);
        continue;
      }

      // Check: enough entries?
      if (weekEntries.length < min_entries) {
        result.skipped.push(`${wk}: only ${weekEntries.length} entries (need ${min_entries}+)`);
        continue;
      }

      // Check: all entries old enough?
      const newestEntry = weekEntries[weekEntries.length - 1];
      const ageMs = Date.now() - new Date(newestEntry.date).getTime();
      const ageDays = ageMs / (1000 * 60 * 60 * 24);
      if (ageDays < min_age_days) {
        result.skipped.push(`${wk}: newest entry ${newestEntry.date} is only ${ageDays.toFixed(0)}d old`);
        continue;
      }

      if (dry_run) {
        result.summariesCreated.push(`${wk} (${weekEntries.length} entries → would create ${summaryFile})`);
        result.entriesArchived += weekEntries.length;
        result.weeksRolledUp++;
        continue;
      }

      // Synthesize weekly summary
      const summary = synthesizeWeek(wk, weekEntries);
      fs.writeFileSync(path.join(dir, summaryFile), summary, "utf-8");
      result.summariesCreated.push(summaryFile);

      // Archive original daily files
      ensureDir(archiveDir);
      for (const entry of weekEntries) {
        const srcPath = path.join(entry.dir, entry.file);
        const destPath = path.join(archiveDir, entry.file);
        if (fs.existsSync(srcPath)) {
          fs.copyFileSync(srcPath, destPath);
          fs.unlinkSync(srcPath);

          // Also archive state file if exists
          const stateSrc = stateFilePath(slug, entry.date);
          if (fs.existsSync(stateSrc)) {
            fs.copyFileSync(stateSrc, path.join(archiveDir, `${entry.date}.state.json`));
            fs.unlinkSync(stateSrc);
          }

          // Archive log file if exists
          const logSrc = path.join(entry.dir, `${entry.date}-log.md`);
          if (fs.existsSync(logSrc)) {
            fs.copyFileSync(logSrc, path.join(archiveDir, `${entry.date}-log.md`));
            fs.unlinkSync(logSrc);
          }
        }
        result.entriesArchived++;
      }

      result.weeksRolledUp++;
    }

    if (!dry_run && result.weeksRolledUp > 0) {
      updateIndex(slug);
    }

    return {
      content: [{
        type: "text" as const,
        text: JSON.stringify({
          project: slug,
          dry_run,
          ...result,
        }),
      }],
    };
  });
}
